version: '3.8'

services:
  mysql_test:
    image: mysql:8.0
    container_name: mysql_test
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: contacts_db_test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest_password"]
      interval: 5s
      timeout: 5s
      retries: 20
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - test-network

  app_test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app_test
    depends_on:
      mysql_test:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - DB_HOST=mysql_test
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=test_password
      - DB_NAME=contacts_db_test
      - JEST_DEBUG=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 10 &&
        npm run test -- --verbose --detectOpenHandles --forceExit
      "
    networks:
      - test-network

volumes:
  mysql_test_data:

networks:
  test-network:
    name: test-network
    driver: bridge 